version: '3.9'

x-environment: &commonEnvironment
  REDIS_HOST: 'redis'
  NODE_ENV: 'development'

services:
  api:
    container_name: devanddeliver_api
    image: api
    platform: linux/x86_64
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - devanddeliver
    env_file:
      - .env
    environment: *commonEnvironment

networks:
  devanddeliver:
